import { formatClinicLocation } from '@/lib/clinic-api';
import type { ReportMeta } from '@/lib/report-api';
import { cn } from '@/lib/utils';

function formatPeriod(dateFrom: string, dateTo: string): string {
  const fmt = (iso: string) =>
    new Date(iso).toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
    });
  return `${fmt(dateFrom)} – ${fmt(dateTo)}`;
}

function formatGeneratedAt(iso: string): string {
  return new Date(iso).toLocaleString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  });
}

interface ReportLayoutProps {
  meta: ReportMeta;
  children: React.ReactNode;
  className?: string;
}

export function ReportLayout({ meta, children, className }: ReportLayoutProps) {
  const address = formatClinicLocation(meta.clinic);

  return (
    <div
      className={cn(
        'overflow-hidden rounded-lg border bg-white shadow-sm print:rounded-none print:border-0 print:shadow-none',
        className,
      )}
    >
      <div className="border-b bg-slate-900 px-6 py-6 text-white print:bg-slate-900 print:text-white">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-300">
              {meta.title}
            </p>
            <h2 className="mt-2 text-2xl font-bold">{meta.clinic.name}</h2>
            {address && <p className="mt-1 text-sm text-slate-300">{address}</p>}
            <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-sm text-slate-300">
              {meta.clinic.phone && <span>Tel: {meta.clinic.phone}</span>}
              {meta.clinic.email && <span>{meta.clinic.email}</span>}
            </div>
          </div>
          <div className="rounded-md border border-slate-700 bg-slate-800/80 px-4 py-3 text-sm">
            <p>
              <span className="text-slate-400">Period:</span>{' '}
              <span className="font-medium">{formatPeriod(meta.dateFrom, meta.dateTo)}</span>
            </p>
            <p className="mt-1">
              <span className="text-slate-400">Generated:</span>{' '}
              <span className="font-medium">{formatGeneratedAt(meta.generatedAt)}</span>
            </p>
            <p className="mt-1">
              <span className="text-slate-400">Generated by:</span>{' '}
              <span className="font-medium">{meta.generatedBy.name}</span>
            </p>
            <p className="text-xs text-slate-400">{meta.generatedBy.email}</p>
          </div>
        </div>
      </div>
      <div className="p-6">{children}</div>
    </div>
  );
}
